notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true

branches:
  only:
    - master
    - develop

image: Visual Studio 2017

platform:
  - x64

configuration:
  - Debug
  - Release

environment:
  BOOST_ROOT: C:\Libraries\boost_1_67_0

install:
    - git submodule update --init --recursive

before_build:
    - cmake -G "Visual Studio 15 2017 Win64" .

build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln

test_script:
  - '%APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\tests.exe'