notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true

branches:
  only:
    - master
    - develop

image: Visual Studio 2017

platform:
  - x64

configuration:
  - Debug
  - Release

environment:
  BOOST_ROOT: C:\Libraries\boost_1_67_0

build_script:
  - md debug
  - cd debug
  - cmake -G "Visual Studio 14 2015 Win64" ..
  - cmake --build . --config Debug
  - ctest
  - cd ..
  - md release
  - cd release
  - cmake -G "Visual Studio 14 2015 Win64" ..
  - cmake --build . --config Release
  - ctest