notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true

branches:
  only:
    - master
    - develop

image: Visual Studio 2017

init:
    - git config --global core.autocrlf input

clone_folder: c:\projects\automarkup
shallow_clone: true

matrix:
    fast_finish: false

platform:
    - x64
    - x86

configuration:
    - Debug
    - Release

install:
    - call ci\appveyor\set-env.bat %TOOLCHAIN% %PLATFORM%
    - appveyor DownloadFile <url> -FileName <local-file>
    - 7z e -y <local-file> -o<local-dir>
    - ...

build_script:
    - mkdir build
    - cd build
    - cmake .. %CMAKE_CONFIGURE_FLAGS%
    - cmake --build . %CMAKE_BUILD_FLAGS%

test_script:
    - ctest -C %CONFIGURATION% --output-on-failure