notifications:
  on_success: change
  on_failure: change

branches:
  only:
    - master
    - develop

language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-7
            - cmake-data
            - cmake
            - libboost-all-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: osx
      language: cpp
      compiler: clang

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir debug
  - cd debug
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - cmake --build .
  - ctest
  - cd ..
  - mkdir release
  - cd release
  - cmake -DCMAKE_BUILD_TYPE=Release ..