notifications:
  on_success: change
  on_failure: change

branches:
  only:
    - master
    - develop

dist: trusty
sudo: required
os:
    - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - g++-7
      - cmake
      - libblkid-dev
      - e2fslibs-dev
      - libboost-all-dev
      - libaudit-dev

language: cpp

script:
  - mkdir build
  - cd build
  - CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7 cmake ..
  - cmake --build .
  - ctest --output-on-failure
  - cmake --build .
