notifications:
  on_success: change
  on_failure: change

branches:
  only:
    - master
    - develop

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - george-edison55-precise-backports
        packages:
          - g++-7
          - cmake
          - libblkid-dev
          - e2fslibs-dev
          - libboost-all-dev
          - libaudit-dev
      env: CXX=/usr/bin/g++-7
    - os: osx
      language: cpp
      compiler: clang

script:
  - mkdir debug
  - cd debug
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - cmake --build .
  - ctest
  - cd ..
  - mkdir release
  - cd release
  - cmake -DCMAKE_BUILD_TYPE=Release ..

