notifications:
  on_success: change
  on_failure: change

branches:
  only:
    - master
    - develop

os: linux
dist: trusty
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - g++-7
      - cmake
      - libblkid-dev
      - e2fslibs-dev
      - libboost-all-dev
      - libaudit-dev

language: cpp

script:
  - CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7 cmake .
  - cmake --build .
