notifications:
  on_success: change
  on_failure: change

branches:
  only:
    - master
    - develop

language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
    - os: osx
      language: cpp
      compiler: clang

script:
  - mkdir debug
  - cd debug
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - cmake --build .
  - ctest
  - cd ..
  - mkdir release
  - cd release
  - cmake -DCMAKE_BUILD_TYPE=Release ..