notifications:
  on_success: change
  on_failure: change

branches:
  only:
    - master
    - develop

language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - george-edison55-precise-backports
        packages:
          - g++-7
          - cmake
          - libblkid-dev
          - e2fslibs-dev
          - libboost-all-dev
          - libaudit-dev
      env:
        - CXX=/usr/bin/g++-7
    - os: osx
      compiler: clang

script:
  - cmake .
  - cmake --build .
