notifications:
  on_success: change
  on_failure: change

branches:
  only:
    - master
    - develop

language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      language: cpp
      compiler: clang

script:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get update -y; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get upgrade -y; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install build-essential software-properties-common -y; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get update -y; fi
  - if [ $TRAVIS_OS_NAME = linux ]; sudo apt-get install gcc-8 g++-8 -y; fi
  - mkdir debug
  - cd debug
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - cmake --build .
  - ctest
  - cd ..
  - mkdir release
  - cd release
  - cmake -DCMAKE_BUILD_TYPE=Release ..

